apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-rene-cp
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.20.0.0/16
    services:
      cidrBlocks:
      - 10.21.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-rene-cp-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-rene-cp-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: eks-rene-cp-control-plane
spec:
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.12.6-eksbuild.2
  - conflictResolution: overwrite
    name: coredns
    version: v1.9.3-eksbuild.3
  - conflictResolution: overwrite
    name: kube-proxy
    version: v1.24.10-eksbuild.2
  disableVPCCNI: false
  eksClusterName: eks-rene-cp
  endpointAccess:
    private: true
    public: true
    publicCIDRs:
    - 0.0.0.0/0
  identityRef:
    kind: AWSClusterStaticIdentity
    name: 9dbf835bed844848acb0fa1ec17a0842-se-aws
  logging:
    apiServer: true
    audit: false
    authenticator: false
    controllerManager: false
    scheduler: false
  network:
    subnets:
    - availabilityZone: us-west-1b
      cidrBlock: 10.0.0.0/20
      isPublic: true
    - availabilityZone: us-west-1b
      cidrBlock: 10.0.128.0/20
      isPublic: false
    - availabilityZone: us-west-1c
      cidrBlock: 10.0.16.0/20
      isPublic: true
    - availabilityZone: us-west-1c
      cidrBlock: 10.0.144.0/20
      isPublic: false
  region: us-west-1
  sshKeyName: jb4key
  version: v1.24
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations: {}
  name: eks-rene-cp-md-0
spec:
  clusterName: eks-rene-cp
  replicas: 3
  selector:
    matchLabels:
      machineDeployment: eks-rene-cp-md-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        machineDeployment: eks-rene-cp-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: eks-rene-cp-md-0
      clusterName: eks-rene-cp
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: eks-rene-cp-md-0
      version: v1.24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: eks-rene-cp-md-0
spec:
  template:
    spec:
      ami: {}
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.large
      sshKeyName: jb4key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: eks-rene-cp-md-0
spec:
  template:
    spec:
      apiRetryAttempts: 1500
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: eks-rene-cp
    sunpike.pf9.io/cluster: eks-rene-cp
    type: monitoring
  name: eks-rene-cp-monitoring
spec:
  override:
    params:
    - name: retentionTime
      value: 7d
  type: monitoring
  version: 0.57.2
  watch: true
