apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: demo
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.20.0.0/16
    services:
      cidrBlocks:
        - 10.21.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: demo-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: demo-control-plane
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: demo-control-plane
  namespace: default
spec:
  addons:
    - name: vpc-cni
      version: v1.12.6-eksbuild.2
      conflictResolution: overwrite
    - name: coredns
      version: v1.9.3-eksbuild.3
      conflictResolution: overwrite
    - name: kube-proxy
      version: v1.24.10-eksbuild.2
      conflictResolution: overwrite
  region: us-west-1
  sshKeyName: jb4key
  version: v1.24
  eksClusterName: demo
  disableVPCCNI: false
  logging:
    apiServer: false
    audit: false
    authenticator: false
    controllerManager: false
    scheduler: false
  endpointAccess:
    private: true
    public: true
    publicCIDRs:
      - 0.0.0.0/0
  identityRef:
    kind: AWSClusterStaticIdentity
    name: 9dbf835bed844848acb0fa1ec17a0842-se-aws
  network:
    subnets:
      - cidrBlock: 10.0.0.0/20
        isPublic: true
        availabilityZone: us-west-1b
      - cidrBlock: 10.0.128.0/20
        isPublic: false
        availabilityZone: us-west-1b
      - cidrBlock: 10.0.16.0/20
        isPublic: true
        availabilityZone: us-west-1c
      - cidrBlock: 10.0.144.0/20
        isPublic: false
        availabilityZone: us-west-1c
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: demo-md-0
  namespace: default
  annotations: {}
spec:
  clusterName: demo
  replicas: 3
  selector:
    matchLabels:
      machineDeployment: demo-md-0
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        machineDeployment: demo-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: demo-md-0
      clusterName: demo
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: demo-md-0
      version: v1.24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: demo-md-0
  namespace: default
spec:
  template:
    spec:
      ami: {}
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.medium
      sshKeyName: jb4key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: demo-md-0
  namespace: default
spec:
  template:
    spec:
      apiRetryAttempts: 1500
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: demo
    type: metrics-server
    clusterName: demo
  name: demo-metrics-server
  namespace: default
spec:
  override:
    params:
      - name: metricsCpuLimit
        value: 100m
      - name: metricsMemoryLimit
        value: 300Mi
  type: metrics-server
  version: 0.5.2
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: demo
    type: kubernetes-dashboard
    clusterName: demo
  name: demo-kubernetes-dashboard
  namespace: default
spec:
  override: {}
  type: kubernetes-dashboard
  version: 2.4.0
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: demo
    type: monitoring
    clusterName: demo
  name: demo-monitoring
  namespace: default
spec:
  override:
    params:
      - name: retentionTime
        value: 7d
  type: monitoring
  version: 0.57.2
  watch: true
