apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster-1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.20.0.0/16
    services:
      cidrBlocks:
      - 10.21.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: NodeletControlPlane
    name: aws-cluster-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: aws-cluster-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: aws-cluster-1
spec:
  controlPlaneLoadBalancer:
    crossZoneLoadBalancing: false
    healthCheckProtocol: TCP
    scheme: internet-facing
  eksClusterName: aws-cluster-1
  identityRef:
    kind: AWSClusterStaticIdentity
    name: 9dbf835bed844848acb0fa1ec17a0842-se-aws
  network:
    cni:
      cniIngressRules:
      - description: bgp (calico)
        fromPort: 179
        protocol: tcp
        toPort: 179
      - description: IP-in-IP (calico)
        fromPort: -1
        protocol: "4"
        toPort: 65535
      - description: calico typha (pf9)
        fromPort: 5473
        protocol: tcp
        toPort: 5473
      - description: node exporter (pf9)
        fromPort: 9100
        protocol: tcp
        toPort: 9100
    subnets:
    - availabilityZone: us-west-1b
      cidrBlock: 10.0.0.0/20
      isPublic: true
    - availabilityZone: us-west-1b
      cidrBlock: 10.0.128.0/20
      isPublic: false
    vpc:
      cidrBlock: 10.0.0.0/16
  region: us-west-1
  sshKeyName: jb4key
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: NodeletControlPlane
metadata:
  name: aws-cluster-1-control-plane
spec:
  apiserver:
    apiGroupsAndVersions: ""
    extraArgs: {}
    privileged: true
  cni:
    calico:
      IPIPMode: Always
      IPv4BlkSize: 26
      IPv4DetectionMethod: first-found
      MTUSize: 1440
      natOutgoing: true
  dns: {}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: aws-cluster-1-control-plane
    nodeletConfigSpec:
      httpProxy: {}
  replicas: 3
  schedulable: false
  version: 1.24.7-pmk.203
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: aws-cluster-1-control-plane
spec:
  template:
    spec:
      ami:
        id: ami-04b7133a525334ceb
      cloudInit:
        insecureSkipSecretsManager: true
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.medium
      nonRootVolumes:
      - deviceName: /dev/xvdb
        size: 100
        type: gp3
      publicIP: false
      rootVolume:
        size: 50
        type: gp3
      sshKeyName: jb4key
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations: {}
  name: aws-cluster-1-md-0
spec:
  clusterName: aws-cluster-1
  replicas: 3
  selector:
    matchLabels:
      machineDeployment: aws-cluster-1-md-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        machineDeployment: aws-cluster-1-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: NodeletConfigTemplate
          name: aws-cluster-1-md-0
      clusterName: aws-cluster-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: aws-cluster-1-md-0
      version: 1.24.7-pmk.203
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: aws-cluster-1-md-0
spec:
  template:
    spec:
      ami:
        id: ami-04b7133a525334ceb
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.medium
      nonRootVolumes:
      - deviceName: /dev/xvdb
        size: 100
        type: gp3
      rootVolume:
        size: 50
        type: gp3
      sshKeyName: jb4key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: NodeletConfigTemplate
metadata:
  name: aws-cluster-1-md-0
spec:
  template:
    spec:
      labels: {}
      taints: []
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: aws-cluster-1
    sunpike.pf9.io/cluster: aws-cluster-1
    type: kubernetes-dashboard
  name: aws-cluster-1-kubernetes-dashboard
spec:
  override: {}
  type: kubernetes-dashboard
  version: 2.4.0
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: aws-cluster-1
    sunpike.pf9.io/cluster: aws-cluster-1
    type: monitoring
  name: aws-cluster-1-monitoring
spec:
  override:
    params:
    - name: retentionTime
      value: 7d
  type: monitoring
  version: 0.57.2
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: aws-cluster-1
    sunpike.pf9.io/cluster: aws-cluster-1
    type: coredns
  name: aws-cluster-1-coredns
spec:
  override:
    params:
    - name: dnsMemoryLimit
      value: 170Mi
    - name: dnsDomain
      value: cluster.local
    - name: CoresPerReplica
      value: "256"
    - name: NodesPerReplica
      value: "16"
    - name: MinReplicas
      value: "1"
    - name: MaxReplicas
      value: "10"
    - name: PollPeriodSecs
      value: "300"
  type: coredns
  version: 1.8.6
  watch: true
